// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.Authorize
{
    [DbContext(typeof(AuthorizeDbContext))]
    [Migration("20251220035858_UpdatePartner")]
    partial class UpdatePartner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Authorize.Address", b =>
                {
                    b.Property<Guid>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressID");

                    b.HasIndex("UserId", "City", "District", "Ward");

                    b.ToTable("Addresses", "auth");
                });

            modelBuilder.Entity("DataAccess.Entities.Authorize.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentOTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPartnerComfirm")
                        .HasColumnType("bit");

                    b.Property<int>("LargeScaleProjectCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastOTPSentAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MediumScaleProjectCount")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("OTPExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("int");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SmallScaleProjectCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "auth");

                    b.HasData(
                        new
                        {
                            Id = "9570d410-e3ea-46e0-aac1-bb17dff7457f",
                            AccessFailedCount = 0,
                            AverageRating = 0.0,
                            ConcurrencyStamp = "9b2687e8-2163-4506-b125-c93c3c711a1d",
                            Email = "homecaredn43@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LargeScaleProjectCount = 0,
                            LockoutEnabled = false,
                            MediumScaleProjectCount = 0,
                            NormalizedEmail = "HOMECAREDN43@GMAIL.COM",
                            NormalizedUserName = "HOMECAREDN43@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM3ylXgLCp6lKUk7ltDMpcVW92RpvpPRV/RNparxAllNA5TrRcD2IGBBxomFRMRCaA==",
                            PhoneNumberConfirmed = false,
                            ProjectCount = 0,
                            RatingCount = 0,
                            ReputationPoints = 0,
                            SecurityStamp = "93a896c5-a844-4f7b-86ed-f09ce2ecad4f",
                            SmallScaleProjectCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "homecaredn43@gmail.com"
                        },
                        new
                        {
                            Id = "cba463ec-27a1-4882-8515-afd8109ae7fa",
                            AccessFailedCount = 0,
                            AverageRating = 0.0,
                            ConcurrencyStamp = "b94ba347-3477-43d5-bc1e-fcf5b3adb03f",
                            Email = "homecaredncontractor@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Contractor",
                            LargeScaleProjectCount = 0,
                            LockoutEnabled = false,
                            MediumScaleProjectCount = 0,
                            NormalizedEmail = "HOMECAREDNCONTRACTOR@GMAIL.COM",
                            NormalizedUserName = "HOMECAREDNCONTRACTOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENE52jv3UYpHXhu4BN9/bjoIVV2QCwVAIM7fpkSIMHbww9LMZI1T/OoEZgOQpnlA9g==",
                            PhoneNumberConfirmed = false,
                            ProjectCount = 0,
                            RatingCount = 0,
                            ReputationPoints = 0,
                            SecurityStamp = "e80a63f1-bffa-4040-b8c8-f28144aabb54",
                            SmallScaleProjectCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "homecaredncontractor@gmail.com"
                        },
                        new
                        {
                            Id = "4e4386ec-e25d-464b-b2a3-ee57ecff614b",
                            AccessFailedCount = 0,
                            AverageRating = 0.0,
                            ConcurrencyStamp = "c2c111be-6ec4-4338-8526-934cb55347c7",
                            Email = "homecaredndistributor@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Distributor",
                            LargeScaleProjectCount = 0,
                            LockoutEnabled = false,
                            MediumScaleProjectCount = 0,
                            NormalizedEmail = "HOMECAREDNDISTRIBUTOR@GMAIL.COM",
                            NormalizedUserName = "HOMECAREDNDISTRIBUTOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECDN46KNkf+vnEcJOA1wY8O4iemLIrHL/xVROgFMT6d3MhsdtpDTvW1wK5GPHGKQrA==",
                            PhoneNumberConfirmed = false,
                            ProjectCount = 0,
                            RatingCount = 0,
                            ReputationPoints = 0,
                            SecurityStamp = "071e4937-65e5-4bec-aeae-f3014c671175",
                            SmallScaleProjectCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "homecaredndistributor@gmail.com"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Authorize.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "auth");

                    b.HasData(
                        new
                        {
                            Id = "fdf4e70c-8bc1-4c63-b78b-0b71b3618f95",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "b8d2f939-6450-41c6-b5f2-d9bc0f1c9f94",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b0e6799f-ea1b-4df1-a0c0-0dc77c4f54cc",
                            Name = "Contractor",
                            NormalizedName = "CONTRACTOR"
                        },
                        new
                        {
                            Id = "d1aa179c-780e-4938-a169-1d18e87f4b2d",
                            Name = "Distributor",
                            NormalizedName = "DISTRIBUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "auth");

                    b.HasData(
                        new
                        {
                            UserId = "9570d410-e3ea-46e0-aac1-bb17dff7457f",
                            RoleId = "b8d2f939-6450-41c6-b5f2-d9bc0f1c9f94"
                        },
                        new
                        {
                            UserId = "cba463ec-27a1-4882-8515-afd8109ae7fa",
                            RoleId = "b0e6799f-ea1b-4df1-a0c0-0dc77c4f54cc"
                        },
                        new
                        {
                            UserId = "4e4386ec-e25d-464b-b2a3-ee57ecff614b",
                            RoleId = "d1aa179c-780e-4938-a169-1d18e87f4b2d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "auth");
                });

            modelBuilder.Entity("DataAccess.Entities.Authorize.Address", b =>
                {
                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccess.Entities.Authorize.RefreshToken", b =>
                {
                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccess.Entities.Authorize.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Authorize.ApplicationUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
