// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204081832_UpdateDistributorStatus")]
    partial class UpdateDistributorStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                {
                    b.Property<Guid>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandDescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BrandLogoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BrandID");

                    b.HasIndex("BrandLogoID");

                    b.ToTable("Brands", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryLogoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryLogoID");

                    b.ToTable("Categories", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ConversationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdminRead")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChatMessageID");

                    b.HasIndex("ConversationID");

                    b.ToTable("ChatMessages", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContactSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactSupports", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                {
                    b.Property<Guid>("ContractorApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueCommisionTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimatePrice")
                        .HasColumnType("float");

                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractorApplicationID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("ContractorApplications", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdminRead")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaterialRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConversationID");

                    b.HasIndex("ServiceRequestID")
                        .IsUnique()
                        .HasFilter("[ServiceRequestID] IS NOT NULL");

                    b.ToTable("Conversations", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                {
                    b.Property<Guid>("DistributorApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DistributorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueCommisionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MaterialRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalEstimatePrice")
                        .HasColumnType("float");

                    b.HasKey("DistributorApplicationID");

                    b.HasIndex("MaterialRequestID");

                    b.ToTable("DistributorApplications", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplicationItem", b =>
                {
                    b.Property<Guid>("DistributorApplicationItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistributorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("DistributorApplicationItemID");

                    b.HasIndex("DistributorApplicationID");

                    b.HasIndex("MaterialID");

                    b.ToTable("DistributorApplicationItems", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Document", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PartnerRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentID");

                    b.HasIndex("ContractorApplicationID");

                    b.HasIndex("PartnerRequestID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("Documents", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Image", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrandID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContractorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MaterialID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PartnerRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReviewID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageID");

                    b.HasIndex("ContractorApplicationID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("PartnerRequestID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("Images", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                {
                    b.Property<Guid>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEN")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Materials", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                {
                    b.Property<Guid>("MaterialRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanAddMaterial")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ConversationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SelectedDistributorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialRequestID");

                    b.HasIndex("ConversationID")
                        .IsUnique()
                        .HasFilter("[ConversationID] IS NOT NULL");

                    b.HasIndex("SelectedDistributorApplicationID")
                        .IsUnique()
                        .HasFilter("[SelectedDistributorApplicationID] IS NOT NULL");

                    b.ToTable("MaterialRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequestItem", b =>
                {
                    b.Property<Guid>("MaterialRequestItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MaterialRequestItemID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("MaterialRequestID");

                    b.ToTable("MaterialRequestItems", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PartnerRequest", b =>
                {
                    b.Property<Guid>("PartnerRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsContractSigned")
                        .HasColumnType("bit");

                    b.Property<string>("PartnerRequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartnerRequestID");

                    b.ToTable("PartnerRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ContractorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("DistributorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MaterialRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentLinkID")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentTransactionID");

                    b.HasIndex("ContractorApplicationID");

                    b.HasIndex("DistributorApplicationID");

                    b.ToTable("PaymentTransactions", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Review", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MaterialRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PartnerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("MaterialRequestID")
                        .IsUnique()
                        .HasFilter("[MaterialRequestID] IS NOT NULL");

                    b.HasIndex("ServiceRequestID")
                        .IsUnique()
                        .HasFilter("[ServiceRequestID] IS NOT NULL");

                    b.ToTable("Review", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Service", b =>
                {
                    b.Property<Guid>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DesignStyle")
                        .HasColumnType("int");

                    b.Property<int?>("MainStructureType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ConversationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("EstimatePrice")
                        .HasColumnType("float");

                    b.Property<int>("Floors")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("MainStructureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SelectedContractorApplicationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("ServiceRequestID");

                    b.HasIndex("ConversationID")
                        .IsUnique()
                        .HasFilter("[ConversationID] IS NOT NULL");

                    b.HasIndex("SelectedContractorApplicationID")
                        .IsUnique()
                        .HasFilter("[SelectedContractorApplicationID] IS NOT NULL");

                    b.ToTable("ServiceRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Image", "LogoImage")
                        .WithMany()
                        .HasForeignKey("BrandLogoID");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Image", "LogoImage")
                        .WithMany()
                        .HasForeignKey("CategoryLogoID");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ChatMessage", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.ServiceRequest", "ServiceRequest")
                        .WithMany("ContractorApplications")
                        .HasForeignKey("ServiceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.MaterialRequest", "MaterialRequest")
                        .WithMany("DistributorApplications")
                        .HasForeignKey("MaterialRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplicationItem", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.DistributorApplication", null)
                        .WithMany("Items")
                        .HasForeignKey("DistributorApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Application.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Document", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.ContractorApplication", null)
                        .WithMany("Documents")
                        .HasForeignKey("ContractorApplicationID");

                    b.HasOne("DataAccess.Entities.Application.PartnerRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("PartnerRequestID");

                    b.HasOne("DataAccess.Entities.Application.Service", null)
                        .WithMany("Documents")
                        .HasForeignKey("ServiceID");

                    b.HasOne("DataAccess.Entities.Application.ServiceRequest", null)
                        .WithMany("Documents")
                        .HasForeignKey("ServiceRequestID");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Image", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.ContractorApplication", null)
                        .WithMany("Images")
                        .HasForeignKey("ContractorApplicationID");

                    b.HasOne("DataAccess.Entities.Application.Material", null)
                        .WithMany("Images")
                        .HasForeignKey("MaterialID");

                    b.HasOne("DataAccess.Entities.Application.PartnerRequest", null)
                        .WithMany("Images")
                        .HasForeignKey("PartnerRequestID");

                    b.HasOne("DataAccess.Entities.Application.Review", null)
                        .WithMany("Images")
                        .HasForeignKey("ReviewID");

                    b.HasOne("DataAccess.Entities.Application.Service", null)
                        .WithMany("Images")
                        .HasForeignKey("ServiceID");

                    b.HasOne("DataAccess.Entities.Application.ServiceRequest", null)
                        .WithMany("Images")
                        .HasForeignKey("ServiceRequestID");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Brand", "Brand")
                        .WithMany("Materials")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Application.Category", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Conversation", "Conversation")
                        .WithOne("MaterialRequest")
                        .HasForeignKey("DataAccess.Entities.Application.MaterialRequest", "ConversationID");

                    b.HasOne("DataAccess.Entities.Application.DistributorApplication", "SelectedDistributorApplication")
                        .WithOne()
                        .HasForeignKey("DataAccess.Entities.Application.MaterialRequest", "SelectedDistributorApplicationID");

                    b.Navigation("Conversation");

                    b.Navigation("SelectedDistributorApplication");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequestItem", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Entities.Application.MaterialRequest", null)
                        .WithMany("MaterialRequestItems")
                        .HasForeignKey("MaterialRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PaymentTransaction", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.ContractorApplication", "ContractorApplication")
                        .WithMany()
                        .HasForeignKey("ContractorApplicationID");

                    b.HasOne("DataAccess.Entities.Application.DistributorApplication", "DistributorApplication")
                        .WithMany()
                        .HasForeignKey("DistributorApplicationID");

                    b.Navigation("ContractorApplication");

                    b.Navigation("DistributorApplication");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Review", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.MaterialRequest", "MaterialRequest")
                        .WithOne("Review")
                        .HasForeignKey("DataAccess.Entities.Application.Review", "MaterialRequestID");

                    b.HasOne("DataAccess.Entities.Application.ServiceRequest", "ServiceRequest")
                        .WithOne("Review")
                        .HasForeignKey("DataAccess.Entities.Application.Review", "ServiceRequestID");

                    b.Navigation("MaterialRequest");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Conversation", "Conversation")
                        .WithOne("ServiceRequest")
                        .HasForeignKey("DataAccess.Entities.Application.ServiceRequest", "ConversationID");

                    b.HasOne("DataAccess.Entities.Application.ContractorApplication", "SelectedContractorApplication")
                        .WithOne()
                        .HasForeignKey("DataAccess.Entities.Application.ServiceRequest", "SelectedContractorApplicationID");

                    b.Navigation("Conversation");

                    b.Navigation("SelectedContractorApplication");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Conversation", b =>
                {
                    b.Navigation("MaterialRequest");

                    b.Navigation("Messages");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                {
                    b.Navigation("DistributorApplications");

                    b.Navigation("MaterialRequestItems");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PartnerRequest", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Service", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                {
                    b.Navigation("ContractorApplications");

                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
