// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                {
                    b.Property<Guid>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandDescription")
                        .HasColumnType("text");

                    b.Property<string>("BrandDescriptionEN")
                        .HasColumnType("text");

                    b.Property<Guid?>("BrandLogoID")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandNameEN")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BrandID");

                    b.HasIndex("BrandLogoID");

                    b.ToTable("Brands", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryLogoID")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CategoryNameEN")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryLogoID");

                    b.ToTable("Categories", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ChatMessage", b =>
                {
                    b.Property<Guid>("ChatMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChatMessageID");

                    b.HasIndex("ConversationID");

                    b.ToTable("ChatMessages", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContactSupport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplyBy")
                        .HasColumnType("text");

                    b.Property<string>("ReplyContent")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactSupports", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                {
                    b.Property<Guid>("ContractorApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractorID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueCommisionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EstimatePrice")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContractorApplicationID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("ContractorApplications", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContractorID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uuid");

                    b.HasKey("ConversationID");

                    b.HasIndex("ServiceRequestID")
                        .IsUnique();

                    b.ToTable("Conversations", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                {
                    b.Property<Guid>("DistributorApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributorID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialRequestID")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("DistributorApplicationID");

                    b.HasIndex("MaterialRequestID");

                    b.ToTable("DistributorApplications", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplicationItem", b =>
                {
                    b.Property<Guid>("DistributorApplicationItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DistributorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialID")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("DistributorApplicationItemID");

                    b.HasIndex("DistributorApplicationID");

                    b.ToTable("DistributorApplicationItems", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Document", b =>
                {
                    b.Property<Guid>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("Documents", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Image", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MaterialID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartnerRequestID")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceRequestID")
                        .HasColumnType("uuid");

                    b.HasKey("ImageID");

                    b.HasIndex("ContractorApplicationID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("PartnerRequestID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("ServiceRequestID");

                    b.ToTable("Images", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                {
                    b.Property<Guid>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NameEN")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("UnitEN")
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaterialID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Materials", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                {
                    b.Property<Guid>("MaterialRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanAddMaterial")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditQuantity")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("SelectedDistributorApplicationDistributorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedDistributorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaterialRequestID");

                    b.HasIndex("SelectedDistributorApplicationDistributorApplicationID");

                    b.ToTable("MaterialRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequestItem", b =>
                {
                    b.Property<Guid>("MaterialRequestItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialRequestID")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MaterialRequestItemID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("MaterialRequestID");

                    b.ToTable("MaterialRequestItems", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PartnerRequest", b =>
                {
                    b.Property<Guid>("PartnerRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PartnerRequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartnerRequestID");

                    b.ToTable("PartnerRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.PaymentTransaction", b =>
                {
                    b.Property<Guid>("PaymentTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ContractorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentLinkID")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ServiceRequestID")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTransactionID");

                    b.HasIndex("ContractorApplicationID");

                    b.ToTable("PaymentTransactions", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Service", b =>
                {
                    b.Property<Guid>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("text");

                    b.Property<int?>("DesignStyle")
                        .HasColumnType("integer");

                    b.Property<int?>("MainStructureType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEN")
                        .HasColumnType("text");

                    b.Property<string>("PackageOption")
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceID");

                    b.ToTable("Services", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                {
                    b.Property<Guid>("ServiceRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConversationID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesignStyle")
                        .HasColumnType("text");

                    b.Property<double?>("EstimatePrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Floors")
                        .HasColumnType("integer");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<string>("MainStructureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SelectedContractorApplicationID")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.HasKey("ServiceRequestID");

                    b.HasIndex("ConversationID")
                        .IsUnique();

                    b.HasIndex("SelectedContractorApplicationID");

                    b.ToTable("ServiceRequests", "app");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Image", "LogoImage")
                        .WithMany()
                        .HasForeignKey("BrandLogoID");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Image", "LogoImage")
                        .WithMany()
                        .HasForeignKey("CategoryLogoID");

                    b.Navigation("LogoImage");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ChatMessage", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.ServiceRequest", "ServiceRequest")
                        .WithMany("ContractorApplications")
                        .HasForeignKey("ServiceRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.MaterialRequest", null)
                        .WithMany("DistributorApplications")
                        .HasForeignKey("MaterialRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplicationItem", b =>
                {
                    b.HasOne("DataAccess.Entities.Application.DistributorApplication", null)
                        .WithMany("Items")
                        .HasForeignKey("DistributorApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    modelBuilder.Entity("DataAccess.Entities.Application.Document", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.ServiceRequest", null)
                                .WithMany("Documents")
                                .HasForeignKey("ServiceRequestID");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Image", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.ContractorApplication", null)
                                .WithMany("Images")
                                .HasForeignKey("ContractorApplicationID");

                            b.HasOne("DataAccess.Entities.Application.Material", null)
                                .WithMany("Images")
                                .HasForeignKey("MaterialID");

                            b.HasOne("DataAccess.Entities.Application.PartnerRequest", null)
                                .WithMany("Images")
                                .HasForeignKey("PartnerRequestID");

                            b.HasOne("DataAccess.Entities.Application.Service", null)
                                .WithMany("Images")
                                .HasForeignKey("ServiceID");

                            b.HasOne("DataAccess.Entities.Application.ServiceRequest", null)
                                .WithMany("Images")
                                .HasForeignKey("ServiceRequestID");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.Brand", "Brand")
                                .WithMany("Materials")
                                .HasForeignKey("BrandID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.HasOne("DataAccess.Entities.Application.Category", "Category")
                                .WithMany("Materials")
                                .HasForeignKey("CategoryID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.Navigation("Brand");

                            b.Navigation("Category");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.DistributorApplication", "SelectedDistributorApplication")
                                .WithMany()
                                .HasForeignKey("SelectedDistributorApplicationDistributorApplicationID");

                            b.Navigation("SelectedDistributorApplication");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequestItem", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.Material", "Material")
                                .WithMany()
                                .HasForeignKey("MaterialID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.HasOne("DataAccess.Entities.Application.MaterialRequest", null)
                                .WithMany("MaterialRequestItems")
                                .HasForeignKey("MaterialRequestID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.Navigation("Material");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.PaymentTransaction", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.ContractorApplication", "ContractorApplication")
                                .WithMany()
                                .HasForeignKey("ContractorApplicationID")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b.Navigation("ContractorApplication");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                        {
                            b.HasOne("DataAccess.Entities.Application.Conversation", "Conversation")
                                .WithOne("ServiceRequest")
                                .HasForeignKey("DataAccess.Entities.Application.ServiceRequest", "ConversationID");

                            b.HasOne("DataAccess.Entities.Application.ContractorApplication", "SelectedContractorApplication")
                                .WithOne()
                                .HasForeignKey("DataAccess.Entities.Application.ServiceRequest", "SelectedContractorApplicationID");

                            b.Navigation("Conversation");

                            b.Navigation("SelectedContractorApplication");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Brand", b =>
                        {
                            b.Navigation("Materials");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Category", b =>
                        {
                            b.Navigation("Materials");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.ContractorApplication", b =>
                        {
                            b.Navigation("Images");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Conversation", b =>
                        {
                            b.Navigation("Messages");

                            b.Navigation("ServiceRequest");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.DistributorApplication", b =>
                        {
                            b.Navigation("Items");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Material", b =>
                        {
                            b.Navigation("Images");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.MaterialRequest", b =>
                        {
                            b.Navigation("DistributorApplications");

                            b.Navigation("MaterialRequestItems");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.PartnerRequest", b =>
                        {
                            b.Navigation("Images");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.Service", b =>
                        {
                            b.Navigation("Images");
                        });

                    modelBuilder.Entity("DataAccess.Entities.Application.ServiceRequest", b =>
                        {
                            b.Navigation("ContractorApplications");

                            b.Navigation("Documents");

                            b.Navigation("Images");
                        });
#pragma warning restore 612, 618
                });
        } 
    }
}
