name: Backend CI

on:
  push:
    branches:
      - '**'   # chạy trên tất cả nhánh khi push
  pull_request:
    branches:
      - develop
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Set Sonar branch name
        run: echo "SONAR_BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=quangvo5803_HomeCareDN
            -Dsonar.organization=quangvo5803
            -Dsonar.branch.name=${{ env.SONAR_BRANCH_NAME }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-test:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore HomeCareDN/HomeCareDN.sln

      - name: Build
        run: dotnet build HomeCareDN/HomeCareDN.sln --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test HomeCareDN/HomeCareDN.sln --no-build --verbosity normal
